"""Build transformed tables and the cash-flow reporting mart from raw extracts.

Reads data/raw/*.json, writes data/transformed/*.json and
data/reporting/cashflow-forecast.json. Stdlib only.

Usage (from repo root):
    python scripts/build_report_data.py
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"
TRANSFORMED = ROOT / "data" / "transformed"
REPORTING = ROOT / "data" / "reporting"

CASH_FLOW_CATEGORIES = [
    {
        "label": "Operating Activities",
        "color": "var(--cat-operating)",
        "inflowKey": "operatingInflow",
        "inflowWhatItRepresents": "Cash generated by day-to-day operations — mining and data center revenue",
        "inflowDriver": "Bitcoin sales + Data center customer payments",
        "outflowKey": "operatingOutflow",
        "outflowWhatItRepresents": "Cash spent running day-to-day operations",
        "outflowDriver": "Mining costs + Other fixed operating costs",
    },
    {
        "label": "Investing Activities",
        "color": "var(--cat-investing)",
        "inflowKey": "investingInflow",
        "inflowWhatItRepresents": "Cash from investing activities, e.g. asset sales or equipment disposals",
        "inflowDriver": "Not modeled in this MVP — always $0",
        "outflowKey": "investingOutflow",
        "outflowWhatItRepresents": "Cash spent building the data center",
        "outflowDriver": "Construction payments (baseline × cost overrun, shifted by delay)",
    },
    {
        "label": "Financing Activities",
        "color": "var(--cat-financing)",
        "inflowKey": "financingInflow",
        "inflowWhatItRepresents": "Cash raised from lenders and investors",
        "inflowDriver": "Debt draws + Equity funding",
        "outflowKey": "financingOutflow",
        "outflowWhatItRepresents": "Cash paid to lenders and investors, e.g. debt service or dividends",
        "outflowDriver": "Not modeled in this MVP — always $0",
    },
]


def load_json(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def dump_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        json.dump(payload, f, indent=2)
        f.write("\n")


def to_float(value) -> float:
    if isinstance(value, str):
        value = value.strip().replace(",", "").replace("%", "")
    return float(value)


def period_to_month_index(year: int, month: int, start_year: int, start_month: int) -> int:
    return (year - start_year) * 12 + (month - start_month) + 1


def parse_period(period: str) -> tuple[int, int]:
    year_s, month_s = period.split("-")
    return int(year_s), int(month_s)


def parse_iso_date(value: str) -> date:
    return date.fromisoformat(value[:10])


def transform(raw_erp: dict, raw_mine: dict, raw_dc: dict, raw_plan: dict) -> dict:
    horizon = raw_plan["horizon"]
    start_year = int(horizon["start_year"])
    start_month = int(horizon["start_month"])
    num_months = int(horizon["num_months"])

    operating_cash = sum(
        to_float(row["balance_usd"])
        for row in raw_erp["cash_and_banks"]
        if row.get("gl_account") == "100100"
    )
    gna = next(
        to_float(row["amount_monthly_usd"])
        for row in raw_erp["opex_run_rate"]
        if row.get("cost_center") == "CC-GNA-001"
    )

    construction = []
    for row in raw_erp["ap_construction_schedule"]:
        pay = parse_iso_date(row["planned_pay_date"])
        construction.append(
            {
                "period": f"{pay.year:04d}-{pay.month:02d}",
                "forecast_month": period_to_month_index(pay.year, pay.month, start_year, start_month),
                "amount_usd": to_float(row["amount_usd"]),
            }
        )
    construction.sort(key=lambda r: r["forecast_month"])

    financing = []
    for row in raw_erp["treasury_events"]:
        value_date = parse_iso_date(row["value_date"])
        kind = "debt_draw" if row["instrument_type"] == "TERM_LOAN" else "equity_funding"
        financing.append(
            {
                "kind": kind,
                "period": f"{value_date.year:04d}-{value_date.month:02d}",
                "forecast_month": period_to_month_index(
                    value_date.year, value_date.month, start_year, start_month
                ),
                "amount_usd": to_float(row["amount_usd"]),
            }
        )

    production = []
    for row in raw_mine["production_forecast"]:
        year, month = parse_period(row["period"])
        production.append(
            {
                "period": row["period"],
                "forecast_month": period_to_month_index(year, month, start_year, start_month),
                "btc": to_float(row["btc_produced"]),
            }
        )
    production.sort(key=lambda r: r["forecast_month"])

    open_year = int(raw_dc["planned_opening"]["year"])
    open_month = int(raw_dc["planned_opening"]["month"])
    ramp = []
    for row in raw_dc["ramp_curve"]:
        pct = row["utilization_pct"]
        fraction = to_float(pct) / 100.0 if isinstance(pct, str) and "%" in pct else to_float(pct)
        ramp.append(fraction)

    drivers = raw_plan["editable_drivers"]

    return {
        "cash_position": {
            "as_of": "2026-09-30",
            "starting_cash_usd": operating_cash,
            "currency": "USD",
        },
        "opex": {
            "other_fixed_opex_monthly_usd": gna,
        },
        "construction_schedule": construction,
        "mining_production": {
            "power_cost_per_btc_usd": to_float(raw_mine["power_cost_per_btc_usd"]),
            "other_mining_opex_monthly_usd": to_float(raw_mine["other_mining_opex_usd_per_month"]),
            "by_month": production,
        },
        "data_center_plan": {
            "monthly_revenue_full_ramp_usd": to_float(raw_dc["monthly_revenue_full_ramp_usd"]),
            "base_open_forecast_month": period_to_month_index(
                open_year, open_month, start_year, start_month
            ),
            "ramp_fractions_after_open": ramp,
        },
        "financing_events": financing,
        "planning_defaults": {
            "start_year": start_year,
            "start_month": start_month,
            "num_months": num_months,
            "btc_price_usd": to_float(drivers["btc_spot_usd"]),
            "cost_overrun_pct": to_float(drivers["construction_cost_overrun_pct"]),
            "delay_months": int(to_float(drivers["construction_delay_months"])),
        },
    }


def series_by_forecast_month(rows: list[dict], num_months: int, value_key: str) -> list[float]:
    out = [0.0] * num_months
    for row in rows:
        idx = row["forecast_month"]
        if 1 <= idx <= num_months:
            out[idx - 1] += row[value_key]
    return out


def first_event(events: list[dict], kind: str) -> dict:
    for row in events:
        if row["kind"] == kind:
            return row
    return {"amount_usd": 0.0, "forecast_month": 1}


def build_reporting(xf: dict) -> dict:
    plan = xf["planning_defaults"]
    n = plan["num_months"]
    mine = xf["mining_production"]
    dc = xf["data_center_plan"]
    debt = first_event(xf["financing_events"], "debt_draw")
    equity = first_event(xf["financing_events"], "equity_funding")
    btc = series_by_forecast_month(mine["by_month"], n, "btc")
    capex = series_by_forecast_month(xf["construction_schedule"], n, "amount_usd")
    while capex and capex[-1] == 0:
        capex.pop()

    return {
        "_note": "Report-specific mart for the cash flow forecast dashboard. Built from data/transformed. Illustrative data only.",
        "forecast": {
            "numMonths": n,
            "startYear": plan["start_year"],
            "startMonth": plan["start_month"],
        },
        "defaultInputs": {
            "btcPrice": plan["btc_price_usd"],
            "costOverrunPct": plan["cost_overrun_pct"],
            "delayMonths": plan["delay_months"],
        },
        "fixedAssumptions": {
            "startingCash": xf["cash_position"]["starting_cash_usd"],
            "dcMonthlyRevenueFullRamp": dc["monthly_revenue_full_ramp_usd"],
            "dcBaseOpenMonth": dc["base_open_forecast_month"],
            "debtDrawAmount": debt["amount_usd"],
            "debtDrawMonth": debt["forecast_month"],
            "equityFundingAmount": equity["amount_usd"],
            "equityFundingMonth": equity["forecast_month"],
        },
        "mining": {
            "btcProductionByMonth": btc,
            "powerCostPerBtc": mine["power_cost_per_btc_usd"],
            "otherMiningOpexMonthly": mine["other_mining_opex_monthly_usd"],
        },
        "construction": {
            "baselinePaymentsByMonth": capex,
        },
        "dataCenter": {
            "rampFractionsAfterOpen": dc["ramp_fractions_after_open"],
        },
        "otherFixedOpexMonthly": xf["opex"]["other_fixed_opex_monthly_usd"],
        "cashFlowCategories": CASH_FLOW_CATEGORIES,
    }


def ints_where_whole(value):
    if isinstance(value, float) and value.is_integer():
        return int(value)
    if isinstance(value, list):
        return [ints_where_whole(v) for v in value]
    if isinstance(value, dict):
        return {k: ints_where_whole(v) for k, v in value.items()}
    return value


def main() -> None:
    raw_erp = load_json(RAW / "erp_finance.json")
    raw_mine = load_json(RAW / "mining_ops.json")
    raw_dc = load_json(RAW / "dc_commercial.json")
    raw_plan = load_json(RAW / "planning.json")

    xf = transform(raw_erp, raw_mine, raw_dc, raw_plan)
    for name, payload in xf.items():
        dump_json(TRANSFORMED / f"{name}.json", ints_where_whole(payload))

    reporting = ints_where_whole(build_reporting(xf))
    dump_json(REPORTING / "cashflow-forecast.json", reporting)
    print(f"Wrote {TRANSFORMED} ({len(xf)} tables)")
    print(f"Wrote {REPORTING / 'cashflow-forecast.json'}")


if __name__ == "__main__":
    main()
